name: Text-KwikiFormatish
version: 1.02
abstract: convert Kwikitext into XML-compliant HTML
author: Ian Langworth <langworth.com>
license: perl
distribution_type: module
requires:
  CGI::Util: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
