# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-KwikiFormatish
version:      1.01
version_from: lib/Text/KwikiFormatish.pm
installdirs:  site
requires:
    CGI::Util:                     

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
